In [0]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/

In [0]:
!ls "/content/drive/My Drive/pre_data"

test  train_preliminary

In [0]:
# !pip install tensorflow
# !pip install numpy
# !pip install pandas
# !pip install xgboost
# !pip install matplotlib
# !pip install keras
# !pip install sklearn

In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn import preprocessing
from tensorflow.keras import datasets, layers, models
from keras.models import Sequential
from keras.layers.embeddings import Embedding
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'

Using TensorFlow backend.

Found GPU at: /device:GPU:0

In [0]:
df1 = pd.read_csv("/content/drive/My Drive/pre_data/train_preliminary/user.csv")
df2 = pd.read_csv("/content/drive/My Drive/pre_data/train_preliminary/ad.csv")
df3 = pd.read_csv("/content/drive/My Drive/pre_data/train_preliminary/click_log.csv")
df = pd.merge(df3, df2, left_on='creative_id', right_on='creative_id')
order = ['user_id', 'time', 'creative_id', 'click_times', 'ad_id', 'product_category', 'advertiser_id']
df = df[order]
df.sort_values(['user_id', 'time'], inplace=True)
df.reset_index(drop=True, inplace=True)
df

          user_id  time  creative_id  ...    ad_id  product_category  advertiser_id
0               1    20       877468  ...   773445                 5          29455
1               1    20       209778  ...   188507                 2           9702
2               1    20       821396  ...   724607                 5           7293
3               1    39      1683713  ...  1458878                 5          14668
4               1    40       122032  ...   109959                 2          11411
...           ...   ...          ...  ...      ...               ...            ...
30082766   900000    57      2692144  ...  2316309                 5          14372
30082767   900000    71      3391205  ...  2918341                 5          22137
30082768   900000    72      3471208  ...  2989104                 5           7283
30082769   900000    74      3527098  ...  3037879                18          14681
30082770   900000    91      4387250  ...  3761723                18          60572

[30082771 rows x 7 columns]

In [0]:
x_tmp = np.array(df['creative_id'])
x_tmp = x_tmp.reshape((-1, 1))
x_tmp = np.vstack((x_tmp, np.zeros((29, 1))))
print(x_tmp.shape)
x_tmp = x_tmp.reshape((-1, 100))
model = Sequential()
model.add(Embedding(5000000, 5, input_length=100))
model.compile(loss='MSE', optimizer='adam')
y_tmp = model.predict(x_tmp, verbose=1)
y_tmp = y_tmp.reshape((-1, 5))
x_tmp = pd.DataFrame(y_tmp[:30082771, :], columns=['creative_id_0', 'creative_id_1', 'creative_id_2', 'creative_id_3', 'creative_id_4'])
X = df[['user_id', 'time', 'click_times']]
X = pd.concat([X, x_tmp], axis=1)
x_tmp = np.array(df['ad_id'])
x_tmp = x_tmp.reshape((-1, 1))
x_tmp = np.vstack((x_tmp, np.zeros((29, 1))))
print(x_tmp.shape)
x_tmp = x_tmp.reshape((-1, 100))
model = Sequential()
model.add(Embedding(4000000, 5, input_length=100))
model.compile(loss='MSE', optimizer='adam')
y_tmp = model.predict(x_tmp, verbose=1)
y_tmp = y_tmp.reshape((-1, 5))
x_tmp = pd.DataFrame(y_tmp[:30082771, :], columns=['ad_id_0', 'ad_id_1', 'ad_id_2', 'ad_id_3', 'ad_id_4'])
X = pd.concat([X, x_tmp], axis=1)
x_tmp = np.array(df['product_category'])
x_tmp = x_tmp.reshape((-1, 1))
x_tmp = np.vstack((x_tmp, np.zeros((29, 1))))
print(x_tmp.shape)
x_tmp = x_tmp.reshape((-1, 100))
model = Sequential()
model.add(Embedding(20, 5, input_length=100))
model.compile(loss='MSE', optimizer='adam')
y_tmp = model.predict(x_tmp, verbose=1)
y_tmp = y_tmp.reshape((-1, 5))
x_tmp = pd.DataFrame(y_tmp[:30082771, :], columns=['product_category_0', 'product_category_1', 
                                                   'product_category_2', 'product_category_3', 'product_category_4'])
X = pd.concat([X, x_tmp], axis=1)
x_tmp = np.array(df['advertiser_id'])
x_tmp = x_tmp.reshape((-1, 1))
x_tmp = np.vstack((x_tmp, np.zeros((29, 1))))
x_tmp = x_tmp.reshape((-1, 100))
model = Sequential()
model.add(Embedding(70000, 5, input_length=100))
model.compile(loss='MSE', optimizer='adam')
y_tmp = model.predict(x_tmp, verbose=1)
y_tmp = y_tmp.reshape((-1, 5))
x_tmp = pd.DataFrame(y_tmp[:30082771, :], columns=['advertiser_id_0', 'advertiser_id_1', 
                                                   'advertiser_id_2', 'advertiser_id_3', 'advertiser_id_4'])
X = pd.concat([X, x_tmp], axis=1)
X

(30082800, 1)
300828/300828 [==============================] - 7s 25us/step
(30082800, 1)
300828/300828 [==============================] - 7s 24us/step
(30082800, 1)
300828/300828 [==============================] - 7s 24us/step
300828/300828 [==============================] - 7s 25us/step

          user_id  time  ...  advertiser_id_3  advertiser_id_4
0               1    20  ...         0.022287         0.033874
1               1    20  ...         0.015341         0.043827
2               1    20  ...         0.006333        -0.006894
3               1    39  ...         0.018877         0.032252
4               1    40  ...        -0.014597        -0.048625
...           ...   ...  ...              ...              ...
30082766   900000    57  ...        -0.023970        -0.019949
30082767   900000    71  ...        -0.040218        -0.006012
30082768   900000    72  ...         0.046125        -0.027040
30082769   900000    74  ...         0.027909        -0.039999
30082770   900000    91  ...        -0.044097         0.048295

[30082771 rows x 23 columns]

In [0]:
x_tmp = None
y_tmp = None
df2 = None
df3 = None
df4 = None
df5 = None
X['time'] = X['time'] / 91
X['click_times'] = X['click_times'] / 152

In [0]:
def check_matrix(x):
    if x.shape[0] >= 30:
        return x.iloc[:30, :]
    else:
        tmp1 = np.zeros((30 - x.shape[0], x.shape[1]))
        tmp1 = pd.DataFrame(tmp1)
        tmp1.columns = x.columns
        return pd.concat([x, tmp1], axis=0)
X = X.groupby('user_id').apply(check_matrix)
X = X.reset_index(drop=True)
X = X.drop('user_id', axis = 1)
X

              time  click_times  ...  advertiser_id_3  advertiser_id_4
0         0.219780     0.006579  ...         0.022287         0.033874
1         0.219780     0.006579  ...         0.015341         0.043827
2         0.219780     0.006579  ...         0.006333        -0.006894
3         0.428571     0.006579  ...         0.018877         0.032252
4         0.439560     0.006579  ...        -0.014597        -0.048625
...            ...          ...  ...              ...              ...
26999995  0.000000     0.000000  ...         0.000000         0.000000
26999996  0.000000     0.000000  ...         0.000000         0.000000
26999997  0.000000     0.000000  ...         0.000000         0.000000
26999998  0.000000     0.000000  ...         0.000000         0.000000
26999999  0.000000     0.000000  ...         0.000000         0.000000

[27000000 rows x 22 columns]

In [0]:
X = np.array(X).reshape((900000, 30, 22))

In [0]:
X_train, X_test = X[:800000, :, :], X[800000:, :, :]
Y2_train, Y2_test = df1.iloc[:800000, 2:3], df1.iloc[800000:, 2:3]
model = models.Sequential()
model.add(layers.Masking(mask_value=0., input_shape=(30, 22)))
model.add(layers.LSTM(32))
model.add(layers.Dense(1))
model.summary()
model.compile(loss='MSE', optimizer='adam')
model.fit(X_train, Y2_train, epochs=100)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking_1 (Masking)          (None, 30, 22)            0
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                7040
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33
=================================================================
Total params: 7,073
Trainable params: 7,073
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.2171
Epoch 2/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.2014
Epoch 3/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1920
Epoch 4/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1849
Epoch 5/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1798
Epoch 6/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1760
Epoch 7/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1727
Epoch 8/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1697
Epoch 9/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1671
Epoch 10/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1649
Epoch 11/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1629
Epoch 12/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1611
Epoch 13/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1593
Epoch 14/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1574
Epoch 15/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1556
Epoch 16/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1540
Epoch 17/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1526
Epoch 18/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1513
Epoch 19/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1501
Epoch 20/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1491
Epoch 21/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1480
Epoch 22/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1470
Epoch 23/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1460
Epoch 24/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1451
Epoch 25/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1442
Epoch 26/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1435
Epoch 27/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1427
Epoch 28/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1421
Epoch 29/100
25000/25000 [==============================] - 135s 5ms/step - loss: 0.1414
Epoch 30/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1407
Epoch 31/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1401
Epoch 32/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1396
Epoch 33/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1390
Epoch 34/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1384
Epoch 35/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1379
Epoch 36/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1374
Epoch 37/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1369
Epoch 38/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1365
Epoch 39/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1359
Epoch 40/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1355
Epoch 41/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1350
Epoch 42/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1345
Epoch 43/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1341
Epoch 44/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1337
Epoch 45/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1333
Epoch 46/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1329
Epoch 47/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1325
Epoch 48/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1321
Epoch 49/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1317
Epoch 50/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1314
Epoch 51/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1310
Epoch 52/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1307
Epoch 53/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1304
Epoch 54/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1301
Epoch 55/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1298
Epoch 56/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1295
Epoch 57/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1292
Epoch 58/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1290
Epoch 59/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1287
Epoch 60/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1284
Epoch 61/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1281
Epoch 62/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1278
Epoch 63/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1276
Epoch 64/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1274
Epoch 65/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1271
Epoch 66/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1269
Epoch 67/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1267
Epoch 68/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1264
Epoch 69/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1262
Epoch 70/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1260
Epoch 71/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1258
Epoch 72/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1256
Epoch 73/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1254
Epoch 74/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1252
Epoch 75/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1250
Epoch 76/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1248
Epoch 77/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1246
Epoch 78/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1244
Epoch 79/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1242
Epoch 80/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1240
Epoch 81/100
25000/25000 [==============================] - 135s 5ms/step - loss: 0.1239
Epoch 82/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1237
Epoch 83/100
25000/25000 [==============================] - 135s 5ms/step - loss: 0.1235
Epoch 84/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1233
Epoch 85/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1232
Epoch 86/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1230
Epoch 87/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1229
Epoch 88/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1227
Epoch 89/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1225
Epoch 90/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1224
Epoch 91/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1222
Epoch 92/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1221
Epoch 93/100
25000/25000 [==============================] - 139s 6ms/step - loss: 0.1220
Epoch 94/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1218
Epoch 95/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1217
Epoch 96/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1215
Epoch 97/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1214
Epoch 98/100
25000/25000 [==============================] - 137s 5ms/step - loss: 0.1212
Epoch 99/100
25000/25000 [==============================] - 136s 5ms/step - loss: 0.1211
Epoch 100/100
25000/25000 [==============================] - 138s 6ms/step - loss: 0.1210

In [0]:
Y2_predict = model.predict(X_test)
Y2_predict = np.round(Y2_predict)
ans = 0 
for i in range(100000):
    if Y2_predict[i] == df1.iloc[i + 800000, 2]:
        ans += 1
print('accurency:', ans / 100000)

accurency: 0.8217

In [0]:
Y1_train, Y1_test = df1.iloc[:800000, 1:2], df1.iloc[800000:, 1:2]
Y1_train = pd.get_dummies(Y1_train['age'])
model2 = models.Sequential()
model2.add(layers.Masking(mask_value=0., input_shape=(30, 22)))
model2.add(layers.LSTM(32))
model2.add(layers.Dense(30, activation = 'relu'))
model2.add(layers.Dense(10, activation = 'softmax'))
model2.summary()
model2.compile(loss='MSE', optimizer='adam')
model2.fit(X_train, Y1_train, epochs = 100, batch_size=32)

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
masking_3 (Masking)          (None, 30, 22)            0
_________________________________________________________________
lstm_3 (LSTM)                (None, 32)                7040
_________________________________________________________________
dense_4 (Dense)              (None, 30)                990
_________________________________________________________________
dense_5 (Dense)              (None, 10)                310
=================================================================
Total params: 8,340
Trainable params: 8,340
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0846
Epoch 2/100
25000/25000 [==============================] - 147s 6ms/step - loss: 0.0841
Epoch 3/100
25000/25000 [==============================] - 145s 6ms/step - loss: 0.0837
Epoch 4/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0834
Epoch 5/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0832
Epoch 6/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0830
Epoch 7/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0828
Epoch 8/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0827
Epoch 9/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0826
Epoch 10/100
25000/25000 [==============================] - 145s 6ms/step - loss: 0.0825
Epoch 11/100
25000/25000 [==============================] - 146s 6ms/step - loss: 0.0823
Epoch 12/100
25000/25000 [==============================] - 145s 6ms/step - loss: 0.0822
Epoch 13/100
25000/25000 [==============================] - 145s 6ms/step - loss: 0.0821
Epoch 14/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0821
Epoch 15/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0820
Epoch 16/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0819
Epoch 17/100
25000/25000 [==============================] - 144s 6ms/step - loss: 0.0818
Epoch 18/100
25000/25000 [==============================] - 143s 6ms/step - loss: 0.0818
Epoch 19/100
25000/25000 [==============================] - 142s 6ms/step - loss: 0.0817
Epoch 20/100
25000/25000 [==============================] - 142s 6ms/step - loss: 0.0816
Epoch 21/100
25000/25000 [==============================] - 142s 6ms/step - loss: 0.0816
Epoch 22/100
25000/25000 [==============================] - 142s 6ms/step - loss: 0.0815
Epoch 23/100
 8724/25000 [=========>....................] - ETA: 1:31 - loss: 0.0815Buffered data was truncated after reaching the output size limit.

In [0]:
Y1_predict = model.predict(X_test)
ans = 0 
for i in range(100000):
    if np.argmax(Y1_predict[i]) == df1.iloc[i + 800000, 1] - 1:
        ans += 1
print('accurency:', ans / 100000)

In [0]:
Y2_predict = model.predict(X)
Y1_predict = model2.predict(X)

In [0]:
import csv
with open('/content/drive/My Drive/pre_data/lstm1_gender.csv', 'w', encoding='utf-8') as csvfile:
    fieldnames = ['user_id', 'predicted_gender']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(900000):
        writer.writerow({'user_id': str(i), 'predicted_gender': str(Y2_predict[i])})

In [0]:
with open('/content/drive/My Drive/pre_data/lstm1_age_one_hot.csv', 'w', encoding='utf-8') as csvfile:
    fieldnames = ['user_id']
    for i in range(10):
        fieldnames.append('predicted_age_' + str(i))
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for i in range(900000):
        a = dict()
        a['user_id'] = str(i)
        for j in range(10):
            a['predicted_age_' + str(i)] = Y2_predict[i][j]
        writer.writerow(a)